import Config

config :peak_tracker, auth_host: "https://auth.peak-tracker.com"

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :peak_tracker,
       PeakTrackerWeb.Endpoint,
       cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: PeakTracker.Finch

# Do not print debug messages in production
config :logger,
  level: :info,
  backends: [:console, Sentry.LoggerBackend]

config :sentry,
  dsn: System.get_env("SENTRY_DSN"),
  environment_name: :prod,
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()],
  tags: %{
    env: "production"
  },
  included_environments: [:prod],
  release: System.get_env("VERSION")

config :peak_tracker, PeakTracker.Mountains,
  graphql: [
    show_raised_errors?: false
  ]

config :peak_tracker, PeakTracker.Accounts,
  graphql: [
    show_raised_errors?: false
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
