defmodule PeakTracker.Repo.Migrations.AddGooglePlacesIdToPeaks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:peaks) do
      add :google_places_id, :text
    end
  end

  def down do
    alter table(:peaks) do
      remove :google_places_id
    end
  end
end
