defmodule PeakTracker.Repo.Migrations.AllowNullForPeaksWikidataId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:peaks) do
      modify(:wikidata_id, :text, null: true)
    end
  end

  def down do
    alter table(:peaks) do
      modify(:wikidata_id, :text, null: false)
    end
  end
end
