defmodule PeakTracker.Repo.Migrations.RemoveUniqueIndexForPeaksWikidataId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(unique_index(:peaks, [:wikidata_id], name: "peaks_wikidata_id_unique_index"))
  end

  def down do
    create(unique_index(:peaks, [:wikidata_id], name: "peaks_wikidata_id_unique_index"))
  end
end
