defmodule PeakTracker.Repo.Migrations.AddDataToPeaks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:peaks) do
      add :osm_id, :bigint, null: false
      add :latitude, :float, null: false
      add :longitude, :float, null: false
      add :elevation, :bigint, null: false
      add :wikipedia, :text
      add :wikidata_id, :text, null: false
    end

    create unique_index(:peaks, [:osm_id], name: "peaks_osm_id_unique_index")

    create unique_index(:peaks, [:wikidata_id], name: "peaks_wikidata_id_unique_index")
  end

  def down do
    drop_if_exists unique_index(:peaks, [:wikidata_id], name: "peaks_wikidata_id_unique_index")

    drop_if_exists unique_index(:peaks, [:osm_id], name: "peaks_osm_id_unique_index")

    alter table(:peaks) do
      remove :wikidata_id
      remove :wikipedia
      remove :elevation
      remove :longitude
      remove :latitude
      remove :osm_id
    end
  end
end
