defmodule PeakTracker.Repo.Migrations.AddSlugToPeaks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:peaks) do
      add :slug, :text, null: false
    end

    create unique_index(:peaks, [:slug], name: "peaks_slug_unique_index")
  end

  def down do
    drop_if_exists unique_index(:peaks, [:slug], name: "peaks_slug_unique_index")

    alter table(:peaks) do
      remove :slug
    end
  end
end
