defmodule PeakTracker.Repo.Migrations.CreateScales do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scales, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true

      add :user_id,
          references(
            :users,
            column: :id,
            name: "scales_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :peak_id,
          references(
            :peaks,
            column: :id,
            name: "scales_peak_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:scales, [:user_id, :peak_id], name: "scales_unique_user_and_peak_index")
  end

  def down do
    drop table(:scales)
  end
end
