defmodule PeakTracker.Repo.Migrations.AdjustPeakId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:peaks) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end
  end

  def down do
    alter table(:peaks) do
      modify :id, :uuid, default: nil
    end
  end
end
