name: CI

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: "strict"
      - name: Cache Elixir dependencies
        uses: actions/cache@v3
        with:
          path: ./deps
          key: deps-${{ hashFiles('mix.lock') }}
      - run: mix deps.get
      - run: mix format

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/peak_tracker_dev
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: "strict"
      - name: Cache Elixir dependencies
        uses: actions/cache@v3
        with:
          path: ./deps
          key: deps-${{ hashFiles('mix.lock') }}
      - run: mix deps.get
      - run: mix test
