name: Fly Deploy

# Only trigger, when the CI workflow succeeded
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          GIT_REVISION=$(git rev-parse --short HEAD) && \
            DATE=$(date +%Y-%m-%dT%H:%M:%S) && \
            VERSION="${DATE}-${GIT_REVISION}" && \
            echo $VERSION && \
            flyctl deploy --remote-only --build-arg VERSION=${VERSION}
